### ISSUE TITLE
Digi beolvasztása a Vodafone-ba

### ISSUE THREAD

**Issue by MMate2007** [kolesar-andras/cellavadasz#9]
Miután a Digi mobil beolvadt a Vodafone-ba szerintem a digis cellákat vodafone-osként lehetne megjeleníteni. Amúgy is ahol nincs a Diginek lefedettsége, ott a Vodafone tornyaira csatlakoznak a Digi mobilosok.

**Comment by kolesar-andras** [comment]
Vodafone nem használja a DIGI bázisállomásait. Nem indokolt Vodafone-ként megjeleníteni őket.
